name:         BuiltWithZo2
highlighter:  pygments
source:       .
destination:  ./_gh_pages
markdown:     kramdown
exclude:      ['README.md', 'node_modules', '*.less']
url:          http://builtwithzo2.com
paginate:     10
encoding:     UTF-8
permalink:    pretty
timezone:     Asia/Ho_Chi_Minh