name:           Built with Zo2
highlighter:    pygments
source:         .
destination:    ./_gh_pages
markdown:       kramdown
exclude:        ['README.md', 'node_modules', '*.less']
url:            http://builtwithzo2.com
paginate:       2
#paginate:      5
paginate_path:  /page/:num
encoding:       UTF-8
permalink:      /:title/
timezone:       Asia/Ho_Chi_Minh

# Custom variables
google_analytics:           UA-48910417-7
google_site_verification:   1zcCEq4g4d_KLBpRbu-I88uaTrLkb6JY7JcORNGo2J4
disqus:                     builtwithzo2